keinpop_run:
	go run mai-platform/cmd/app

keinpop_swagger:
	/Users/keinpop/go/bin/swag init -g ./cmd/app/main.go -o ./docs

nyamerka_run:
	go run /Users/Nyamerka/GolandProjects/MAI_Practice/social-platform/backend/cmd/app

