// Package docs Code generated by swaggo/swag. DO NOT EDIT
package docs

import "github.com/swaggo/swag"

const docTemplate = `{
    "schemes": {{ marshal .Schemes }},
    "swagger": "2.0",
    "info": {
        "description": "{{escape .Description}}",
        "title": "{{.Title}}",
        "contact": {},
        "version": "{{.Version}}"
    },
    "host": "{{.Host}}",
    "basePath": "{{.BasePath}}",
    "paths": {
        "/company": {
            "post": {
                "description": "Usage example: 'curl -X POST -v -H \"Content-Type: application/json\" -d '{\"title\":\"Yandex\"}' http://localhost:8080/api/company'",
                "consumes": [
                    "application/json"
                ],
                "produces": [
                    "application/json"
                ],
                "tags": [
                    "Company-API"
                ],
                "summary": "post new company in db",
                "responses": {
                    "200": {
                        "description": "OK",
                        "schema": {
                            "$ref": "#/definitions/company.Company"
                        }
                    }
                }
            },
            "delete": {
                "description": "Usage Example: 'curl -X DELETE -v -H \"Content-Type: application/json\" -d '{\"title\":\"JetBrains\"}' http://localhost:8080/api/company/'",
                "consumes": [
                    "application/json"
                ],
                "produces": [
                    "application/json"
                ],
                "tags": [
                    "Company-API"
                ],
                "summary": "delete company in db",
                "responses": {
                    "200": {
                        "description": "OK",
                        "schema": {}
                    }
                }
            }
        },
        "/company/list": {
            "get": {
                "description": "Usage example: 'curl http://localhost:8080/api/company/list'",
                "consumes": [
                    "application/json"
                ],
                "produces": [
                    "application/json"
                ],
                "tags": [
                    "Company-API"
                ],
                "summary": "get all companies in db",
                "responses": {
                    "200": {
                        "description": "OK",
                        "schema": {
                            "type": "array",
                            "items": {
                                "$ref": "#/definitions/company.Company"
                            }
                        }
                    }
                }
            }
        },
        "/programm": {
            "post": {
                "description": "Usage example: 'curl -X POST -v -H \"Content-Type: application/json\" -d '{\"title\":\"ПМИ\"}' http://localhost:8080/api/programm'",
                "consumes": [
                    "application/json"
                ],
                "produces": [
                    "application/json"
                ],
                "tags": [
                    "Programm-API"
                ],
                "summary": "post new programm in db",
                "responses": {
                    "200": {
                        "description": "OK",
                        "schema": {
                            "$ref": "#/definitions/programm.Programm"
                        }
                    }
                }
            },
            "delete": {
                "description": "Usage example: 'curl -X DELETE -v -H \"Content-Type: application/json\" -d '{\"title\":\"ФИИТ\"}' http://localhost:8080/api/programm/'",
                "consumes": [
                    "application/json"
                ],
                "produces": [
                    "application/json"
                ],
                "tags": [
                    "Programm-API"
                ],
                "summary": "delete programm in db",
                "responses": {
                    "200": {
                        "description": "OK",
                        "schema": {
                            "$ref": "#/definitions/programm.Programm"
                        }
                    }
                }
            }
        },
        "/programm/list": {
            "get": {
                "description": "Usage example: 'curl http://localhost:8080/api/programm/list'",
                "consumes": [
                    "application/json"
                ],
                "produces": [
                    "application/json"
                ],
                "tags": [
                    "Programm-API"
                ],
                "summary": "get all programmes in db",
                "responses": {
                    "200": {
                        "description": "OK",
                        "schema": {
                            "type": "array",
                            "items": {
                                "$ref": "#/definitions/programm.Programm"
                            }
                        }
                    }
                }
            }
        },
        "/role": {
            "post": {
                "description": "Usage example: 'curl -X POST -v -H \"Content-Type: application/json\" -d '{\"title\":\"Backend-разработчик\"}' http://localhost:8080/api/role'",
                "consumes": [
                    "application/json"
                ],
                "produces": [
                    "application/json"
                ],
                "tags": [
                    "Role-API"
                ],
                "summary": "post new role in db",
                "responses": {
                    "200": {
                        "description": "OK",
                        "schema": {
                            "$ref": "#/definitions/role.Role"
                        }
                    }
                }
            },
            "delete": {
                "description": "Usage example: 'curl -X DELETE -v -H \"Content-Type: application/json\" -d '{\"title\":\"Frontend-разработчик\"}' http://localhost:8080/api/role/'",
                "consumes": [
                    "application/json"
                ],
                "produces": [
                    "application/json"
                ],
                "tags": [
                    "Role-API"
                ],
                "summary": "delete role in db",
                "responses": {
                    "200": {
                        "description": "OK",
                        "schema": {
                            "$ref": "#/definitions/role.Role"
                        }
                    }
                }
            }
        },
        "/role/list": {
            "get": {
                "description": "Usage example: 'curl http://localhost:8080/api/role/list'",
                "consumes": [
                    "application/json"
                ],
                "produces": [
                    "application/json"
                ],
                "tags": [
                    "Role-API"
                ],
                "summary": "get all roles in db",
                "responses": {
                    "200": {
                        "description": "OK",
                        "schema": {
                            "type": "array",
                            "items": {
                                "$ref": "#/definitions/role.Role"
                            }
                        }
                    }
                }
            }
        },
        "/technology": {
            "post": {
                "description": "Usage example: 'curl -X POST -v -H \"Content-Type: application/json\" -d '{\"title\":\"Golang\"}' http://localhost:8080/api/technology'",
                "consumes": [
                    "application/json"
                ],
                "produces": [
                    "application/json"
                ],
                "tags": [
                    "Techonology-API"
                ],
                "summary": "post new technology in db",
                "responses": {
                    "200": {
                        "description": "OK",
                        "schema": {
                            "$ref": "#/definitions/technology.Techonology"
                        }
                    }
                }
            },
            "delete": {
                "description": "Usage example: 'curl -X DELETE -v -H \"Content-Type: application/json\" -d '{\"title\":\"Python\"}' http://localhost:8080/api/technology/'",
                "consumes": [
                    "application/json"
                ],
                "produces": [
                    "application/json"
                ],
                "tags": [
                    "Techonology-API"
                ],
                "summary": "delete technology in db",
                "responses": {
                    "200": {
                        "description": "OK",
                        "schema": {
                            "$ref": "#/definitions/technology.Techonology"
                        }
                    }
                }
            }
        },
        "/technology/list": {
            "get": {
                "description": "Usage example: 'curl http://localhost:8080/api/technology/list'",
                "consumes": [
                    "application/json"
                ],
                "produces": [
                    "application/json"
                ],
                "tags": [
                    "Techonology-API"
                ],
                "summary": "get all technologies in db",
                "responses": {
                    "200": {
                        "description": "OK",
                        "schema": {
                            "type": "array",
                            "items": {
                                "$ref": "#/definitions/technology.Techonology"
                            }
                        }
                    }
                }
            }
        }
    },
    "definitions": {
        "company.Company": {
            "type": "object",
            "properties": {
                "id": {
                    "type": "integer"
                },
                "title": {
                    "type": "string"
                }
            }
        },
        "programm.Programm": {
            "type": "object",
            "properties": {
                "duration": {
                    "type": "integer"
                },
                "id": {
                    "type": "integer"
                },
                "title": {
                    "type": "string"
                }
            }
        },
        "role.Role": {
            "type": "object",
            "properties": {
                "id": {
                    "type": "integer"
                },
                "title": {
                    "type": "string"
                }
            }
        },
        "technology.Techonology": {
            "type": "object",
            "properties": {
                "id": {
                    "type": "integer"
                },
                "title": {
                    "type": "string"
                }
            }
        }
    }
}`

// SwaggerInfo holds exported Swagger Info so clients can modify it
var SwaggerInfo = &swag.Spec{
	Version:          "",
	Host:             "",
	BasePath:         "/api",
	Schemes:          []string{},
	Title:            "",
	Description:      "",
	InfoInstanceName: "swagger",
	SwaggerTemplate:  docTemplate,
	LeftDelim:        "{{",
	RightDelim:       "}}",
}

func init() {
	swag.Register(SwaggerInfo.InstanceName(), SwaggerInfo)
}
