basePath: /api/v1
definitions:
  models.Programm:
    properties:
      duration:
        type: integer
      id:
        type: integer
      title:
        type: string
    type: object
info:
  contact: {}
paths:
  /api/programm:
    delete:
      consumes:
      - application/json
      description: delete programm in db
      produces:
      - application/json
      responses:
        "200":
          description: OK
          schema:
            $ref: '#/definitions/models.Programm'
      summary: delete programm in db
    post:
      consumes:
      - application/json
      description: post new programm in db
      produces:
      - application/json
      responses:
        "200":
          description: OK
          schema:
            $ref: '#/definitions/models.Programm'
      summary: post new programm in db
  /api/programm/list:
    get:
      consumes:
      - application/json
      description: get all programm in db
      produces:
      - application/json
      responses:
        "200":
          description: OK
          schema:
            $ref: '#/definitions/models.Programm'
      summary: get all programm in db
swagger: "2.0"
